version: '3.6'
services:
  svn:
    container_name: svn-server
    image: vince-forty3/svn-server-ubuntu
    ports:
    - "80:80"
    - "443:443"
    - "3960:3960"
    volumes:
    - ./volumes/svn:/home/svn
    restart: unless-stopped
